runmode: debug                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: course              # API Server的名字
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/course.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7

gormlog: true

db:
  username: root
  password: 123456
  addr: localhost:3306
  database: course
